export const splashTexts = [
    'React Edition',
    'Made with React',
    'Made in JavaScript!',
    'Made with Three.js',
    'npm install',
    'npm run dev',
    'console.log("Hello World")',
    'index.html',
    'Math.random()',
    'Button.jsx',
    'package.json',
    'Loading...',
    '<playername> IS YOU',
    'Should not be played while driving',
    'HESOYAM',
    'Here we go again',
    'Press any key to continue',
    'Kamehameha',
    'Not on Steam!',
    'Siuuu',
    '90% are bugs',
    'Soon GOTY',
    'I am from the future',
    'Why are you reading this?',
    'You are awesome',
    'Now with more bugs',
    'Now why doesn\'t this work?',
    'I wrote this on 30/12/2023',
    'I watched Midudev\'s tutorial',
    'Supports 4K',
    'I am "Ironman"',
    'I need to sleep :(',
    'Made by "real" people!',
    '100% more yellow text!',
    'How many texts are there?',
    'Don\'t forget to save!',
    'Bugs are features',
    'My name is "Player"',
    'Insert coin',
    '<insert splash text here!>',
    'Drink water!',
    'Someone is watching you',
    '.env is not a secret',
    'I am a splash text',
    '300702',
    'TCP/IP is just a fad!',
    'UwU',
    'Does anyone read this?',
    'I have something to tell you...',
    'HELP!',
]